In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd
import csv               #import the csv package

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies =pd.read_csv("Movie+Assignment+Data.csv")     #importing the csv file
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
movies.shape     #inspecting the number of rows and columns (rows, columns)

(5043, 28)

In [5]:
movies.info()    #inspecting the meta-data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [6]:
movies.describe()      #statistical summary of the DataFrame

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [7]:
movies.isnull().sum()     #column-wise null count

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
movies.isnull().sum(axis=1)      #row-wise null count

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [9]:
round(100*(movies.isnull().sum()/len(movies.index)),2)       #column-wise null percentages

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [10]:
movies= movies.drop('color', axis=1)       #code for dropping the column 'color'
movies

In [11]:
movies= movies.drop('director_facebook_likes', axis=1)        #code for dropping the column 'director_facebook_likes'
movies

In [12]:
movies= movies.drop('actor_1_facebook_likes', axis=1)         #code for dropping the column 'actor_1_facebook_likes'
movies

In [13]:
movies= movies.drop('actor_2_facebook_likes', axis=1)         #code for dropping the column 'actor_2_facebook_likes'
movies

In [14]:
movies= movies.drop('actor_3_facebook_likes', axis=1)         #code for dropping the column 'actor_3_facebook_likes'
movies

In [15]:
movies= movies.drop('actor_2_name', axis=1)                   #code for dropping the column 'actor_2_name'
movies

In [16]:
movies= movies.drop('cast_total_facebook_likes', axis=1)      #code for dropping the column 'cast_total_facebook_likes'
movies

In [17]:
movies= movies.drop('actor_3_name', axis=1)                   #code for dropping the column 'actor_3_name'
movies

In [18]:
movies= movies.drop('duration', axis=1)                       #code for dropping the column 'duration'
movies

In [19]:
movies= movies.drop('facenumber_in_poster', axis=1)           #code for dropping the column 'facenumber_in_poster'
movies

In [20]:
movies= movies.drop('content_rating', axis=1)                 #code for dropping the column 'content_rating'
movies

In [21]:
movies= movies.drop('country', axis=1)                        #code for dropping the column 'country'
movies

In [22]:
movies= movies.drop('movie_imdb_link', axis=1)                #code for dropping the column 'movie_imdb_link'
movies

In [23]:
movies= movies.drop('aspect_ratio', axis=1)                  #code for dropping the column 'aspect_ratio'
movies

In [24]:
movies= movies.drop('plot_keywords', axis=1)                 #code for dropping the column 'plot_keywords'
movies

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [25]:
movies=movies[pd.notnull(movies['gross'])]      #code for dropping the rows which have null values for the column 'gross'

In [26]:
movies=movies[pd.notnull(movies['budget'])]     #code for dropping the rows which have null values for the column 'budget'

In [27]:
round(100*(movies.isnull().sum()/len(movies.index)),2)         #inspecting the column-wise null percentages

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [28]:
movies[movies.isnull().sum(axis=1)>5]         #code for dropping the rows having greater than five NaN values

Empty DataFrame
Columns: [director_name, num_critic_for_reviews, gross, genres, actor_1_name, movie_title, num_voted_users, num_user_for_reviews, language, budget, title_year, imdb_score, movie_facebook_likes]
Index: []

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [29]:
movies.loc[pd.isnull(movies['language']), ['language']] = 'English'    #code for filling the NaN values in the 'language' column as English

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [30]:
movies.shape    #code for checking number of retained rows

(3891, 13)

In [ ]:
                #code for checking the percentage of the rows retained

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [31]:
movies['budget']=round(movies.budget/1000000,2)        #code for unit conversion from $ to million $ in the column 'budget'

In [32]:
movies['gross']=round(movies.gross/1000000,2)          #code for unit conversion from $ to million $ in the column 'gross'

In [33]:
movies.rename(columns={'gross':'gross_in_millions'}, inplace=True)      #code for changing the column name
movies.rename(columns={'budget':'budget_in_millions'}, inplace=True)

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [34]:
movies['profit_in_millions'] = movies['gross_in_millions'] - movies['budget_in_millions']   #code for creating the profit column

In [35]:
movies.sort_values(by='profit_in_millions',ascending=False, inplace=True)   #code for sorting the dataframe with 'profit_in_millions' column as the reference

In [36]:
top10 = movies.nlargest(10, 'profit_in_millions')     #code to get the top 10 profiting movies
top10

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.51
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.18
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.94
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.45
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
17,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.78
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.54
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.32

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [37]:
top10.drop_duplicates()        #code for dropping duplicate values

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.51
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.18
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.94
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.45
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.78
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.54
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.32

In [38]:
movies.drop_duplicates()        #code for repeating subtask 2 after dropping duplicate values
movies.sort_values(by='profit_in_millions',ascending=False, inplace=True)
top10 = movies.nlargest(10, 'profit_in_millions')
top10

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.51
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.18
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.94
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.45
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
17,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.78
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.54
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.32

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [39]:
voted_users=movies.loc[movies.num_voted_users>25000, :]      #code for making sure 'num_voted_users' is greater than 25,000
voted_users.sort_values(by='imdb_score',ascending=False, inplace=True)
IMDb_Top_250 = voted_users.nlargest(250, 'imdb_score')      #code for extracting the top 250 movies as per the IMDb score

In [40]:
initial_value=1          #code for creating the 'Rank' column
IMDb_Top_250['Rank'] = range(initial_value, len(IMDb_Top_250) +initial_value)
IMDb_Top_250 = IMDb_Top_250.set_index('Rank')
IMDb_Top_250

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions
Rank,,,,,,,,,,,,,,
1,Frank Darabont,199.0,28.34,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.34
2,Francis Ford Coppola,208.0,134.82,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.82
3,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.32
4,Francis Ford Coppola,149.0,57.30,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.30
5,Steven Spielberg,174.0,96.07,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.07
6,Sergio Leone,181.0,6.10,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.90
7,Peter Jackson,328.0,377.02,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.02
8,Quentin Tarantino,215.0,107.93,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.93
9,Peter Jackson,297.0,313.84,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.84
10,David Fincher,315.0,37.02,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.98
11,Irvin Kershner,223.0,290.16,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.16
12,Robert Zemeckis,149.0,329.69,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.69
13,Christopher Nolan,642.0,292.57,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.57
14,Milos Forman,149.0,112.00,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.60
15,Fernando Meirelles,214.0,7.56,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.26
16,Peter Jackson,294.0,340.48,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.48
17,Akira Kurosawa,153.0,0.27,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.73
18,Martin Scorsese,192.0,46.84,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.84
19,Lana Wachowski,313.0,171.38,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.38
20,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.94
21,Steven Spielberg,219.0,216.12,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.12
22,Charles Chaplin,120.0,0.16,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.34
23,Hayao Miyazaki,246.0,10.05,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.95
24,Jonathan Demme,185.0,130.73,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.73
25,Tony Kaye,162.0,6.71,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.79
26,Christopher Nolan,712.0,187.99,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.99
27,Bryan Singer,162.0,23.27,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.27
28,David Fincher,216.0,100.13,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.13
29,Quentin Tarantino,765.0,162.80,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.00,2012.0,8.5,199000,62.80
30,Christopher Nolan,813.0,448.13,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.00,2012.0,8.5,164000,198.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,Christophe Barratier,112.0,3.63,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.87
222,Duncan Jones,415.0,5.01,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.01
223,Paul Haggis,287.0,54.56,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.06
224,Paul Haggis,287.0,54.56,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.06
225,Don Hall,384.0,222.49,Action|Adventure|Animation|Comedy|Drama|Family...,Damon Wayans Jr.,Big Hero 6,279093,433.0,English,165.00,2014.0,7.9,41000,57.49
226,Cristian Mungiu,233.0,1.19,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.60
227,John Carpenter,318.0,47.00,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.70
228,John Carpenter,318.0,47.00,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.70
229,Peter Jackson,509.0,258.36,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.36
230,Doug Liman,249.0,121.47,Action|Mystery|Thriller,Matt Damon,The Bourne Identity,407601,849.0,English,60.00,2002.0,7.9,0,61.47
231,Dean DeBlois,292.0,177.00,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,32.00
232,Quentin Tarantino,596.0,54.12,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44.00,2015.0,7.9,114000,10.12
233,Yash Chopra,29.0,2.92,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.08
234,Clint Eastwood,251.0,13.75,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.25
235,Philip Kaufman,80.0,21.50,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271,170.0,English,27.00,1983.0,7.9,0,-5.50
236,Paul Greengrass,491.0,107.10,Biography|Drama|Thriller,Tom Hanks,Captain Phillips,323353,527.0,English,55.00,2013.0,7.9,65000,52.10
237,John Carney,232.0,9.44,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.26
238,David O. Russell,410.0,93.57,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.57
239,Edward Zwick,60.0,26.83,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.83
240,Edward Zwick,60.0,26.83,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.83
241,Jonathan Dayton,270.0,59.89,Comedy|Drama,Steve Carell,Little Miss Sunshine,355810,889.0,English,8.00,2006.0,7.9,15000,51.89
242,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.51
243,Nick Cassavetes,177.0,0.06,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,29.00,2004.0,7.9,57000,-28.94
244,Jon Favreau,486.0,318.30,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.30
245,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92
246,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92
247,F. Gary Gray,349.0,161.03,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.03
248,Cameron Crowe,149.0,32.52,Adventure|Comedy|Drama|Music,Philip Seymour Hoffman,Almost Famous,207287,822.0,English,60.00,2000.0,7.9,15000,-27.48
249,Michael Mann,209.0,28.97,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.03
250,Alfonso Cuarón,372.0,35.29,Drama|Sci-Fi|Thriller,Charlie Hunnam,Children of Men,361767,1206.0,English,76.00,2006.0,7.9,17000,-40.71

In [41]:
Top_Foreign_Lang_Film = IMDb_Top_250.loc[IMDb_Top_250.language!='English', :]        #code to extract top foreign language films from 'IMDb_Top_250'
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions
Rank,,,,,,,,,,,,,,
6,Sergio Leone,181.0,6.10,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.90
15,Fernando Meirelles,214.0,7.56,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.26
17,Akira Kurosawa,153.0,0.27,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.73
23,Hayao Miyazaki,246.0,10.05,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.95
32,Florian Henckel von Donnersmarck,215.0,11.28,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.00,2006.0,8.5,39000,9.28
43,Majid Majidi,46.0,0.93,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.18,1997.0,8.5,0,0.75
47,Chan-wook Park,305.0,2.18,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.00,2003.0,8.4,43000,-0.82
50,Jean-Pierre Jeunet,242.0,33.20,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,77.00,2001.0,8.4,39000,-43.80
54,Wolfgang Petersen,96.0,11.43,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,14.00,1981.0,8.4,11000,-2.57
57,Asghar Farhadi,354.0,7.10,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.50,2011.0,8.4,48000,6.60
58,S.S. Rajamouli,44.0,6.50,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.03,2015.0,8.4,21000,-11.53
60,Hayao Miyazaki,174.0,2.30,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.00,1997.0,8.4,11000,-2397.70
73,Thomas Vinterberg,349.0,0.61,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.80,2012.0,8.3,60000,-3.19
80,Fritz Lang,260.0,0.03,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.00,1927.0,8.3,12000,-5.97
85,Oliver Hirschbiegel,192.0,5.50,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.50,2004.0,8.3,14000,-8.00
86,Guillermo del Toro,406.0,37.62,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.50,2006.0,8.2,27000,24.12
91,Denis Villeneuve,226.0,6.86,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.80,2010.0,8.2,37000,0.06
101,Hayao Miyazaki,212.0,4.71,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.00,2004.0,8.2,13000,-19.29
106,Juan José Campanella,262.0,20.17,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.00,2009.0,8.2,33000,18.17
113,Je-kyu Kang,86.0,1.11,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.80,2004.0,8.1,0,-11.69
116,José Padilha,142.0,0.01,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.00,2007.0,8.1,11000,-3.99
127,Alejandro Amenábar,157.0,2.09,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10.00,2004.0,8.1,0,-7.91
142,Alejandro G. Iñárritu,157.0,5.38,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.00,2000.0,8.1,11000,3.38
144,Thomas Vinterberg,98.0,1.65,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.30,1998.0,8.1,5000,0.35
147,Katsuhiro Ôtomo,150.0,0.44,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.00,1988.0,8.1,0,-1099.56
155,Sergio Leone,122.0,3.50,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.20,1964.0,8.0,0,3.30
173,Karan Johar,210.0,4.02,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.00,2010.0,8.0,27000,-7.98
176,Walter Salles,71.0,5.60,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.90,1998.0,8.0,0,2.70
179,Vincent Paronnaud,242.0,4.44,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.30,2007.0,8.0,14000,-2.86
194,Ari Folman,231.0,2.28,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.50,2008.0,8.0,0,0.78
215,Michael Haneke,447.0,0.23,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.90,2012.0,7.9,33000,-8.67
220,Fabián Bielinsky,94.0,1.22,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.28
221,Christophe Barratier,112.0,3.63,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.87
226,Cristian Mungiu,233.0,1.19,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.60
233,Yash Chopra,29.0,2.92,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.08
234,Clint Eastwood,251.0,13.75,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.25
245,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92
246,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [42]:
arrangebymean = movies.groupby('director_name', as_index=False)['imdb_score'].mean()
arrangebymean.sort_values(by='imdb_score',ascending=False, inplace=True)
top10directors = arrangebymean.nlargest(10, 'imdb_score')      #code for extracting the top 10 directors
top10directors

              director_name  imdb_score
216         Charles Chaplin    8.600000
1675              Tony Kaye    8.600000
302         Damien Chazelle    8.500000
1440             Ron Fricke    8.500000
45         Alfred Hitchcock    8.500000
1017           Majid Majidi    8.500000
1498           Sergio Leone    8.433333
260       Christopher Nolan    8.425000
1035  Marius A. Markevicius    8.400000
1467         S.S. Rajamouli    8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [43]:
movies['genre_1'] = movies['genres'].str.split('|').str[0]      #code for extracting the first two genres of each movie
movies['genre_2'] = movies['genres'].str.split('|').str[1]
movies['genre_2'] = movies['genre_2'].fillna(movies['genre_1'])
movies

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions,genre_1,genre_2
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.51,Action,Adventure
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.00,2015.0,7.0,150000,502.18,Action,Adventure
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.00,1997.0,7.7,26000,458.67,Drama,Romance
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.94,Action,Adventure
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.45,Family,Sci-Fi
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.00,2012.0,8.1,123000,403.28,Action,Adventure
17,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.00,2012.0,8.1,123000,403.28,Action,Adventure
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.00,1994.0,8.5,17000,377.78,Adventure,Animation
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.00,1999.0,6.5,13000,359.54,Action,Adventure
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.32,Action,Crime
439,Gary Ross,673.0,408.00,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.00,2012.0,7.3,140000,330.00,Adventure,Drama
812,Tim Miller,579.0,363.02,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.00,2016.0,8.1,117000,305.02,Action,Adventure
186,Francis Lawrence,502.0,424.65,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.00,2013.0,7.6,82000,294.65,Adventure,Sci-Fi
697,Steven Spielberg,308.0,356.78,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.00,1993.0,8.1,19000,293.78,Adventure,Sci-Fi
521,Pierre Coffin,306.0,368.05,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.00,2013.0,7.5,56000,292.05,Animation,Comedy
814,Clint Eastwood,490.0,350.12,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.80,2014.0,7.3,112000,291.32,Action,Biography
338,Andrew Stanton,301.0,380.84,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.00,2003.0,8.2,11000,286.84,Adventure,Animation
582,Andrew Adamson,205.0,436.47,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.00,2004.0,7.2,0,286.47,Adventure,Animation
339,Peter Jackson,328.0,377.02,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.02,Action,Adventure
1536,Richard Marquand,197.0,309.13,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.50,1983.0,8.4,14000,276.63,Action,Adventure
836,Robert Zemeckis,149.0,329.69,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.69,Comedy,Drama
2051,Irvin Kershner,223.0,290.16,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.16,Action,Adventure
2601,Chris Columbus,102.0,285.76,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.00,1990.0,7.5,20000,267.76,Comedy,Family
236,George Lucas,359.0,380.26,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.00,2005.0,7.6,10000,267.26,Action,Adventure
161,Sam Raimi,291.0,403.71,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.00,2002.0,7.3,5000,264.71,Action,Adventure
563,Kyle Balda,308.0,336.03,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.00,2015.0,6.4,70000,262.03,Action,Animation
1181,M. Night Shyamalan,234.0,293.50,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.00,1999.0,8.1,14000,253.50,Drama,Mystery
2917,Steven Spielberg,385.0,260.00,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.00,1975.0,8.0,21000,252.00,Adventure,Drama
125,Chris Buck,406.0,400.74,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.00,2013.0,7.6,58000,250.74,Adventure,Animation
519,Yarrow Cheney,165.0,323.51,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.00,2016.0,6.8,36000,248.51,Animation,Comedy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,Joe Wright,256.0,34.96,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.00,2015.0,5.8,24000,-115.04,Adventure,Family
3879,Joe Wright,256.0,34.96,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.00,2015.0,5.8,24000,-115.04,Adventure,Family
145,Joe Wright,256.0,34.96,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.00,2015.0,5.8,24000,-115.04,Adventure,Family
113,Oliver Stone,248.0,34.29,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.00,2004.0,5.5,0,-120.71,Action,Adventure
14,Gore Verbinski,450.0,89.29,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.00,2013.0,6.5,48000,-125.71,Action,Adventure
143,Simon Wells,132.0,21.38,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.00,2011.0,5.4,0,-128.62,Action,Adventure
62,Lana Wachowski,384.0,47.38,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.00,2015.0,5.4,44000,-128.62,Action,Adventure
49,Bryan Singer,338.0,65.17,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.00,2013.0,6.3,22000,-129.83,Adventure,Fantasy
85,Carl Rinsch,218.0,38.30,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.00,2013.0,6.3,35000,-136.70,Action,Adventure
2339,Jean-Marie Poiré,8.0,0.15,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,French,140.00,1998.0,6.0,136,-139.85,Comedy,Family
28,Peter Berg,377.0,65.17,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.00,2012.0,5.9,44000,-143.83,Action,Adventure
1782,Jacques Perrin,100.0,10.76,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.00,2001.0,8.0,1000,-149.24,Documentary,Documentary
3877,R. Balki,12.0,0.20,Comedy|Drama,Vidya Balan,Paa,7295,49.0,Hindi,150.00,2009.0,7.2,504,-149.80,Comedy,Drama
91,Robert Zemeckis,188.0,0.67,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.00,2004.0,6.6,10000,-164.33,Adventure,Animation
3659,Prachya Pinkaew,112.0,11.91,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.00,2005.0,7.1,0,-188.09,Action,Crime
5,Andrew Stanton,462.0,73.06,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.70,2012.0,6.6,24000,-190.64,Action,Adventure
2740,Tony Jaa,110.0,0.10,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,Thai,300.00,2008.0,6.2,0,-299.90,Action,Action
1016,Luc Besson,111.0,14.13,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.00,1999.0,6.4,0,-375.87,Adventure,Biography
3311,Chatrichalerm Yukol,31.0,0.45,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,Thai,400.00,2001.0,6.6,124,-399.55,Action,Adventure
1338,John Woo,160.0,0.63,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.63,2008.0,7.4,0,-553.00,Action,Adventure
3273,Anurag Basu,41.0,1.60,Action|Drama|Romance|Thriller,Bárbara Mori,Kites,9673,106.0,English,600.00,2010.0,6.0,0,-598.40,Action,Drama
3075,Karan Johar,20.0,3.28,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,Hindi,700.00,2006.0,6.0,659,-696.72,Drama,Drama
3851,Carlos Saura,35.0,1.69,Drama|Musical,Mía Maestro,Tango,2412,40.0,Spanish,700.00,1998.0,7.2,539,-698.31,Drama,Musical
4542,Takao Okawara,107.0,10.04,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,Japanese,1000.00,1999.0,6.0,339,-989.96,Action,Adventure
3423,Katsuhiro Ôtomo,150.0,0.44,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.00,1988.0,8.1,0,-1099.56,Action,Animation
2334,Katsuhiro Ôtomo,105.0,0.41,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.52,2004.0,6.9,973,-2127.11,Action,Adventure
2323,Hayao Miyazaki,174.0,2.30,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.00,1997.0,8.4,11000,-2397.70,Adventure,Animation
3005,Lajos Koltai,73.0,0.20,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.00,2005.0,7.1,607,-2499.80,Drama,Romance
3859,Chan-wook Park,202.0,0.21,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.00,2005.0,7.7,4000,-4199.79,Crime,Drama
2988,Joon-ho Bong,363.0,2.20,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.50,2006.0,7.0,7000,-12213.30,Comedy,Drama

In [44]:
movies_by_segment = movies.groupby(['genre_1','genre_2'], as_index=False)['gross_in_millions'].mean()    #code for grouping the dataframe
movies_by_segment.sort_values(by='gross_in_millions',ascending=False, inplace=True)
movies_by_segment

         genre_1      genre_2  gross_in_millions
83        Family       Sci-Fi         434.950000
28     Adventure       Sci-Fi         228.628750
18     Adventure    Animation         116.998462
24     Adventure       Family         116.520000
1         Action    Adventure         110.382566
85       Fantasy      Mystery         100.610000
31     Animation       Comedy          97.781515
2         Action    Animation          92.681250
93       Musical      Romance          92.085000
23     Adventure        Drama          91.501613
25     Adventure      Fantasy          90.618182
10        Action      Mystery          90.329333
33     Animation       Family          86.267143
15        Action          War          77.090000
32     Animation        Drama          74.197500
27     Adventure      Mystery          72.098333
14        Action     Thriller          71.553043
12        Action       Sci-Fi          70.787576
59         Crime      Romance          69.300000
42        Comedy       Family          68.584714
11        Action      Romance          67.630000
17     Adventure    Adventure          67.165000
80         Drama      Western          67.102500
60         Crime     Thriller          62.603125
98       Romance       Sci-Fi          62.450000
0         Action       Action          59.521667
86       Fantasy      Romance          56.360000
53        Comedy      Western          56.006667
20     Adventure       Comedy          55.844038
6         Action        Drama          55.567176
..           ...          ...                ...
21     Adventure        Crime          22.447500
7         Action       Family          22.060000
48        Comedy      Mystery          21.850000
19     Adventure    Biography          19.542353
40        Comedy  Documentary          19.306667
67         Drama        Drama          18.866364
94       Mystery      Romance          15.960000
102      Western      Western          15.913333
47        Comedy      Musical          13.703750
16        Action      Western          13.260000
57         Crime       Horror          13.241000
45        Comedy       Horror          12.442857
82        Family        Music          10.410000
54         Crime  Documentary           7.170000
13        Action        Sport           7.010000
61   Documentary  Documentary           5.878750
22     Adventure  Documentary           3.760000
63   Documentary      History           3.670000
30     Animation    Biography           3.360000
81        Family      Fantasy           2.120000
87       Fantasy     Thriller           1.490000
66   Documentary          War           1.430000
36     Biography  Documentary           1.096667
44        Comedy      History           0.630000
65   Documentary        Sport           0.596667
89        Horror      Musical           0.140000
97       Romance      Romance           0.105000
101     Thriller     Thriller           0.040000
99        Sci-Fi       Sci-Fi           0.020000
29     Adventure          War           0.010000

[103 rows x 3 columns]

In [45]:
PopGenre = movies_by_segment.nlargest(5, 'gross_in_millions')        #code for getting the 5 most popular combo of genres
PopGenre

      genre_1    genre_2  gross_in_millions
83     Family     Sci-Fi         434.950000
28  Adventure     Sci-Fi         228.628750
18  Adventure  Animation         116.998462
24  Adventure     Family         116.520000
1      Action  Adventure         110.382566

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [46]:
Meryl_Streep = movies.loc[movies['actor_1_name'] == 'Meryl Streep', :]  #including all movies in which 'Meryl Streep' is the lead

In [47]:
Leo_Caprio = movies.loc[movies['actor_1_name'] == 'Leonardo DiCaprio', :]    #including all movies in which 'Leonardo DiCaprio' is the lead

In [48]:
Brad_Pitt = movies.loc[movies['actor_1_name'] == 'Brad Pitt', :]    #including all movies in which 'Brad Pitt' is the lead

In [49]:
temp=Meryl_Streep.append(Leo_Caprio, ignore_index=True)  #code for combining the three dataframes
Combined = temp.append(Brad_Pitt, ignore_index=True)
Combined

,director_name,num_critic_for_reviews,gross_in_millions,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget_in_millions,title_year,imdb_score,movie_facebook_likes,profit_in_millions,genre_1,genre_2
0,David Frankel,208.0,124.73,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.73,Comedy,Drama
1,Sydney Pollack,66.0,87.10,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.10,Biography,Drama
2,Nora Ephron,252.0,94.13,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.13,Biography,Drama
3,David Frankel,234.0,63.54,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.54,Comedy,Drama
4,Nancy Meyers,187.0,112.70,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.70,Comedy,Drama
5,Phyllida Lloyd,331.0,29.96,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.96,Biography,Drama
6,Stephen Daldry,174.0,41.60,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.60,Drama,Romance
7,Robert Altman,211.0,20.34,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.34,Comedy,Drama
8,Curtis Hanson,42.0,46.82,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.82,Action,Adventure
9,Carl Franklin,64.0,23.21,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.79,Drama,Drama
10,Robert Redford,227.0,15.00,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.00,Drama,Thriller
11,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67,Drama,Romance
12,Christopher Nolan,642.0,292.57,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.57,Action,Adventure
13,Steven Spielberg,194.0,164.44,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.44,Biography,Crime
14,Quentin Tarantino,765.0,162.80,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.80,Drama,Western
15,Alejandro G. Iñárritu,556.0,183.64,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.64,Adventure,Drama
16,Martin Scorsese,490.0,127.97,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.97,Mystery,Thriller
17,Martin Scorsese,352.0,132.37,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.37,Crime,Drama
18,Baz Luhrmann,490.0,144.81,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.81,Drama,Romance
19,Baz Luhrmann,490.0,144.81,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.81,Drama,Romance
20,Baz Luhrmann,106.0,46.34,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.84,Drama,Romance
21,Randall Wallace,83.0,56.88,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.88,Action,Adventure
22,Martin Scorsese,606.0,116.87,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.87,Biography,Comedy
23,Clint Eastwood,392.0,37.30,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.30,Biography,Crime
24,Martin Scorsese,267.0,102.61,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.39,Biography,Drama
25,Danny Boyle,118.0,39.78,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.22,Adventure,Drama
26,Jerry Zaks,45.0,12.78,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.22,Drama,Drama
27,Sam Mendes,323.0,22.88,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.12,Drama,Romance
28,Sam Raimi,63.0,18.64,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.36,Action,Thriller
29,Martin Scorsese,233.0,77.68,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.32,Crime,Drama
30,Ridley Scott,238.0,39.38,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.62,Action,Drama
31,Edward Zwick,166.0,57.37,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.63,Adventure,Drama
32,Steven Soderbergh,186.0,183.41,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.41,Crime,Thriller
33,Doug Liman,233.0,186.34,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.34,Action,Comedy
34,Neil Jordan,120.0,105.26,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.26,Drama,Fantasy
35,David Ayer,406.0,85.71,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.71,Action,Drama
36,Steven Soderbergh,198.0,125.53,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.53,Crime,Thriller
37,Alejandro G. Iñárritu,285.0,34.30,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.30,Drama,Drama
38,Andrew Dominik,414.0,14.94,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.06,Crime,Thriller
39,Tony Scott,122.0,12.28,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.72,Action,Crime
40,Angelina Jolie Pitt,131.0,0.53,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.47,Drama,Romance
41,Terrence Malick,584.0,13.30,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.70,Drama,Fantasy
42,David Fincher,362.0,127.49,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.51,Drama,Fantasy
43,David Fincher,315.0,37.02,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.98,Drama,Drama
44,Andrew Dominik,273.0,3.90,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.10,Biography,Crime
45,Jean-Jacques Annaud,76.0,37.90,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.10,Adventure,Biography
46,Patrick Gilmore,98.0,26.29,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.71,Adventure,Animation
47,Wolfgang Petersen,220.0,133.23,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.77,Adventure,Adventure
48,Tony Scott,142.0,0.03,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.97,Action,Crime

In [50]:
pregrouped = Combined.groupby(['actor_1_name'])     #code for grouping the combined dataframe
Grouped = pregrouped['num_critic_for_reviews','num_user_for_reviews'].mean()
Grouped

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818

In [51]:
Final = Grouped.sort_values(by=['num_critic_for_reviews','num_user_for_reviews'], ascending=False) #code for finding the mean of critic reviews and audience reviews
Final

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      245.000000            742.352941
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!